# -*- coding: utf-8 -*-
"""calculadoraComHistoricoPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T1dbit77Fbhf-hbbb7myy61wRFOlJrVt
"""

pip install numpy

from ast import Mult
import numpy as np
import os
from functools import reduce
ativador=True
while ativador:
  print('SEJA BEM VINDO A CALCULADORA DE DANIEL!!!!!')
  print('\nSELECIONA UMA OPÇAO A SEGUIR:')
  print('SOMAR[0]\nSUBTRAIR[1]\nDIVIDIR[2]\nMULTIPLICAR[3]\nEXIT[4]')
  resposta= int(input(': '))
  if(resposta == 0):
    valores =input('DIGITE VALORES A SER SOMADO: ').split(' ')
    valores_1 = list(map(lambda x: float(x),valores))
    soma = sum(valores_1)
    print(f'RESULTADO: {soma}')
    if os.path.isfile('./historico_calculadora.csv'):
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
        fp.write(f'{str(valores_1)}, {soma}\n')

    else:
      with open(file='./historico_calculadora.csv', mode='w', encoding='utf8') as fp:
        fp.write('VALORES, RESULTADO\n')
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
         fp.write(f'{str(valores_1)}, {soma}\n')
  elif(resposta == 1):
    valores =input('DIGITE VALORES A SER SUBTRAIDO [NUMERO A SER SUBTRAIDO], [...SUBTRAIDOR]: ').split(' ')
    valores_1 = list(map(lambda x: float(x),valores))
    subt = reduce(lambda x, y: x-y, valores_1)
    print(f'RESULTADO: {subt}')
    if os.path.isfile('./historico_calculadora.csv'):
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
        fp.write(f'{str(valores_1)}, {subt}\n')

    else:
      with open(file='./historico_calculadora.csv', mode='w', encoding='utf8') as fp:
        fp.write('VALORES, RESULTADO\n')
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
         fp.write(f'{str(valores_1)}, {subt}\n')
  elif(resposta == 2):
    valores =input('DIGITE VALORES A SER dividido [NUMERO A SER dividido], [o divididador]: ').split(' ')
    valores_1 = list(map(lambda x: float(x),valores))
    divid = reduce(lambda x, y: x/y, valores_1)
    print(f'RESULTADO: {divid}')
    if os.path.isfile('./historico_calculadora.csv'):
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
        fp.write(f'{str(valores_1)}, {divid}\n')

    else:
      with open(file='./historico_calculadora.csv', mode='w', encoding='utf8') as fp:
        fp.write('VALORES, RESULTADO\n')
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
         fp.write(f'{str(valores_1)}, {divid}\n')
  elif(resposta== 3):
    valores =input('DIGITE VALORES A SER MULTIPLICADO : ').split(' ')
    valores_1 = list(map(lambda x: float(x),valores))
    mult = reduce(lambda x, y: x*y, valores_1)
    print(f'RESULTADO: {mult}')
    if os.path.isfile('./historico_calculadora.csv'):
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
        fp.write(f'{str(valores_1)}, {mult}\n')

    else:
      with open(file='./historico_calculadora.csv', mode='w', encoding='utf8') as fp:
        fp.write('VALORES, RESULTADO\n')
      with open(file='./historico_calculadora.csv', mode='a', encoding='utf8') as fp:
         fp.write(f'{str(valores_1)}, {mult}\n')
  elif(resposta==4):
    print('saindo do progama\n dev:  @dfbradom')
    ativador= False

lista = [1,2,3,4,5,6]
print(str(lista).replace('[', '').replace(']', ''))